### ISSUE TITLE
Dark mode does not remember whether to include PDF

### ISSUE THREAD

**Issue by smeingast** [fjwillemsen/NativeOverleaf#7] opened 2022-08-29 07:44 UTC
I always work in dark mode, but prefer the PDF to be displayed regularly, so I deselect the "Include PDF" button in the app menu. However, when quitting/reopening the app, this setting is always reset and the PDF is displayed in dark mode, too, so I always have to manually toggle the "Include PDF". Perhaps it would be possible for the app to remember the settings?

**Comment by fjwillemsen** [comment] 2022-08-29 17:05
You are right, this was caused by a bug I just fixed in the [latest release](https://github.com/fjwillemsen/NativeOverleaf/releases/latest) (v1.7.1). Thank you for reporting! If it is not fixed, feel free to re-open this issue.

**Comment by fjwillemsen** [comment] 2022-08-29 17:06
You are right, this was caused by a bug I just fixed in the [latest release](https://github.com/fjwillemsen/NativeOverleaf/releases/latest) (v1.7.1). Thank you for reporting! If it is not fixed, feel free to re-open this issue.

**Closed by fjwillemsen** 2022-08-29 17:06 UTC
