### ISSUE TITLE
Download PDF button does not work

### ISSUE THREAD

**Issue by mahyarrs** [fjwillemsen/NativeOverleaf#5] opened 2022-08-22 04:29 UTC

**Comment by fjwillemsen** [comment] 2022-08-22 06:35
Thank you for submitting this issue. I am unable to reproduce it on the latest version (1.7.0). Both the download button in the menu as well as the download button in the PDF viewer work for me. Could you give me the version you're on and the steps needed to reproduce it?

**Comment by fjwillemsen** [comment] 2022-08-30 12:50
@mahyarrs could you give some more details on this issue?

**Comment by fjwillemsen** [comment] 2022-09-01 09:33
Given the lack of information provided and inability to reproduce, I am closing this issue for now. Will reopen when new information is provided.

**Closed by fjwillemsen** 2022-09-01 09:33 UTC
Labels: bug, question
