### ISSUE TITLE
Old natifier build error at startup

### ISSUE THREAD

**Issue by tldata1** [fjwillemsen/NativeOverleaf#16] opened 2023-03-01 11:20 UTC
Error on startup:
![image](https://user-images.githubusercontent.com/90393878/222125185-05fe375c-2578-48de-a592-73a7371fb7f2.png)

**Comment by fjwillemsen** [comment] 2023-03-02 11:48
Yes, I have encountered the same warning. The problem is that Nativefier itself hasn't been updated since November, so I didn't release a security update either. A simple recompile will solve this though, so I'll launch a new version today or tomorrow.

**Comment by fjwillemsen** [comment] 2023-03-02 22:33
Fixed in [version 1.8.0](https://github.com/fjwillemsen/NativeOverleaf/releases/tag/v1.8.0).

**Closed by fjwillemsen** 2023-03-02 22:33 UTC
Labels: runtime error
